# Display help message
help:
  @echo "Available commands:"
  @echo "  help          - Show this help message"
  @echo "  create        - Create a new day project, e.g. 01"
  @echo "  get-input     - Get input for a day, e.g. 01"
  @echo "  run           - Run day, e.g. 01 1"
  @echo "  test          - Run day tests, e.g. 01 1 or 01 \"\" for both parts"
  @echo "  bench         - Run day benchmarks, e.g. 01 1 or 01 \"\" for both parts"
  @echo "  dhat          - Run dhat heap memory profiler, e.g. 01 1"

# Crate new day project
create day:
  cargo generate --path ./daily-template --name day{{ day }}
  just get-input {{ day }}

# Get input for a day
get-input day:
  ./fetch.sh {{ day }}

# Run day
run day part:
  cargo run --package day{{ day }} --bin part{{ part }}

# Run day tests
test day part:
  cargo nextest run -p day{{ day }} part{{ part }}

# Run day benchmarks
bench day part:
  cargo bench --bench day{{ day }}-bench-divan part{{ part }} >> day{{ day }}.bench.txt

# Run dhat heap memory profiler
dhat day part:
  cargo run --profile dhat --features dhat-heap --package day{{ day }} --bin part{{ part }}
